version: '3.7'

services:
#PHP 7.4-fpm
  php:
    build:
      context: services/php
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}_php'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - APP_ENV=${APP_ENV}
    volumes:
      - ${APP_PATH}:${WORKING_DIR}
      - ./services/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
    networks:
      net: {}
#NGINX nginx-proxy
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}_nginx'
    volumes:
      - ${APP_PATH}:${WORKING_DIR}
      - ./services/nginx/logs:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      net: {}
#MYSQL 8.0.19
  mysql:
    build:
      context: services/mysql
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}_mysql'
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      net: {}

  # https://hub.docker.com/_/rabbitmq/
  redis:
    image: redis:7.0.2-bullseye
    container_name: '${PROJECT_NAME}_redis'
    #command: '--requirepass kimono'
    ports:
      - "6379"
    networks:
      net: {}

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      HTTP_USER: root
      HTTP_PASSWORD: qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      net: { }

volumes:
  mysql_volume:

networks:
  net:
    name: '${NET_NAME}'
